import { knowledgeEvolution } from "./api.js";
import { renderTenantSelector } from "./tenant.js";

const loginForm = document.querySelector("#login-form"); const workspace = document.querySelector("#workspace"); const status = document.querySelector("#status"); const suggestions = document.querySelector("#suggestions"); const tenantContainer = document.querySelector("#tenant-selector"); let token = sessionStorage.getItem("dictionary-admin-token");

async function refreshTenant() {
  if (tenantContainer && token) await renderTenantSelector(tenantContainer, token, () => load());
}
function setStatus(message, error = false) { status.textContent = message; status.className = error ? "status error" : "status"; }
function config() { return window.APP_CONFIG; }
function render(items) {
  suggestions.replaceChildren(); if (!items.length) { suggestions.textContent = "Ainda não há sugestões."; return; }
  items.forEach((item) => { const card = document.createElement("article"); card.className = "suggestion"; const title = document.createElement("h2"); title.textContent = `${item.suggestion_type} · ${item.status}`; const proposal = document.createElement("p"); proposal.textContent = item.proposal.rationale || item.proposal.proposed_category || "Sem justificativa."; const details = document.createElement("pre"); details.textContent = JSON.stringify(item.proposal, null, 2); card.append(title, proposal, details); if (item.status === "pending") { const actions = document.createElement("div"); actions.className = "admin-actions"; [true, false].forEach((approved) => { const button = document.createElement("button"); button.type = "button"; button.textContent = approved ? "Aprovar" : "Rejeitar"; if (!approved) button.className = "secondary"; button.addEventListener("click", async () => { try { await knowledgeEvolution("review", token, { suggestion_id: item.id, approved }); await load(); } catch (error) { setStatus(error.message, true); } }); actions.append(button); }); card.append(actions); } suggestions.append(card); });
}
async function load() { if (!token) return; try { const data = await knowledgeEvolution("list", token); render(data.suggestions || []); setStatus(`${(data.suggestions || []).filter((item) => item.status === "pending").length} sugestões pendentes.`); } catch (error) { setStatus(error.message, true); } }
async function login(event) { event.preventDefault(); const { supabaseUrl, supabaseAnonKey } = config(); try { const response = await fetch(`${supabaseUrl.replace(/\/$/, "")}/auth/v1/token?grant_type=password`, { method: "POST", headers: { "Content-Type": "application/json", apikey: supabaseAnonKey }, body: JSON.stringify({ email: document.querySelector("#email").value, password: document.querySelector("#password").value }) }); const data = await response.json(); if (!response.ok || !data.access_token) throw new Error(data.error_description || "Não foi possível entrar."); token = data.access_token; sessionStorage.setItem("dictionary-admin-token", token); sessionStorage.setItem("auth-token", token); loginForm.hidden = true; workspace.hidden = false; await refreshTenant(); await load(); } catch (error) { window.alert(error.message); } }
loginForm.addEventListener("submit", login); document.querySelector("#refresh").addEventListener("click", load); document.querySelector("#generate").addEventListener("click", async () => { setStatus("Gerando propostas…"); try { const data = await knowledgeEvolution("generate", token); setStatus(`${data.created} sugestões novas foram registradas.`); await load(); } catch (error) { setStatus(error.message, true); } }); document.querySelector("#logout").addEventListener("click", () => { sessionStorage.removeItem("dictionary-admin-token"); sessionStorage.removeItem("auth-token"); token = null; workspace.hidden = true; loginForm.hidden = false; }); if (token) { loginForm.hidden = true; workspace.hidden = false; refreshTenant(); load(); }
